helm:
  parameters:
  - name: image.name
    value: omniasaad/todo-app
    forcestring: true
  - name: image.tag
    value: 20250730-0147
    forcestring: true
  - name: app.image
    value: omniasaad/todo-app:20250730-0211
    forcestring: true
