# Simple Todo App Configuration
replicaCount: 2

app:  
  image: omniasaad0/todo-app:20250727-2309

  imagePullPolicy: Always
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 4000

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# MongoDB Configuration
mongodb:
  enabled: true
  image:
    repository: mongo
    tag: "6.0"
  auth:
    rootUsername: admin
    rootPassword: pass
    database: todo-list
  persistence:
    enabled: true
    size: 1Gi
  service:
    type: ClusterIP
    port: 27017

# Application Configuration
app_config:
  port: 4000
  mongoDbUrl: "mongodb://admin:pass@todo-app-mongodb:27017/todo-list?authSource=admin" 