apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo-app.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.app.port | quote }}
  mongoDbUrl: {{ .Values.app.mongoDbUrl | quote }} 