apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: "todo-app:latest"
        ports:
        - containerPort: 4000
        env:
        - name: PORT
          value: "4000"
        - name: mongoDbUrl
          value: "mongodb://admin:pass@todo-app-mongodb:27017/todo-list?authSource=admin"
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi 