apiVersion: v1
kind: Service
metadata:
  name: todo-app-mongodb
  namespace: todo-app
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    app: mongodb 