apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: todo-app
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/mongodb"
  storageClassName: local-path
